lmsimpacta/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

from core.views import index, contato, cursos

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contato/', contato, name="contato"),
    url(r'^curriculo/', include('curriculo.urls', namespace='curriculo')),
    url(r'^restrito/', include('restrito.urls', namespace='restrito')),
    url(r'^entrar/$', auth_views.login,{'template_name': 'login.html'}, name='login'),
    url(r'^sair/$', auth_views.logout, name='logout'),
    url(r'^$',index, name="index")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restrito/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import aluno, professor, matricula, questao_form

urlpatterns = [
    url(r'^aluno/$', aluno, name="aluno"),
    url(r'^aluno/matricula', matricula, name="matricula"),
    url(r'^professor/$', professor, name="professor"),
    url(r'^professor/(?P<turma_id>[0-9]+)/questao/(?P<questao_id>[0-9]*)', questao_form, name="questao_form"),
]

restrito/models.py
from django.db import models

def diretorio_questao(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'turma/{0}/questao/{1}/{2}'.format(instance.turma.id, instance.numero, filename)

class Questao(models.Model):

    turma = models.ForeignKey("curriculo.Turma")
    numero = models.SmallIntegerField("Número")
    data_limite_entrega = models.DateTimeField("Entrega")
    descricao = models.TextField("Descrição")
    data = models.DateTimeField("Início")
    arquivo = models.FileField(upload_to=diretorio_questao)

    class Meta:
        db_table = 'QUESTAO'
        unique_together = (('turma', 'numero'),)

restrito/forms.py
from django import forms

from .models import Questao

class DateTextInput(forms.widgets.TextInput):
    input_type = 'datetime-local'

class QuestaoForm(forms.ModelForm):
    data = forms.DateTimeField(input_formats=[
        '%d/%m/%Y %H:%M'
    ])
    data_limite_entrega = forms.DateTimeField(input_formats=[
        '%d/%m/%Y %H:%M'
    ])

    class Meta:
        model = Questao
        exclude = ['turma']

restrito/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.urlresolvers import reverse

from curriculo.models import Turma, DisciplinaOfertada

from .models import Questao
from .checkers import check_aluno, check_professor
from .forms import QuestaoForm

@login_required(login_url="/entrar")
@user_passes_test(check_aluno, login_url="/")
def aluno(request):
    contexto = {
        "turmas": Turma.objects.filter(alunos__parent_link=request.user)
    }
    return render(request,"restrito/aluno.html",contexto)

@login_required(login_url="/entrar")
@user_passes_test(check_aluno, login_url="/")
def matricula(request):
    contexto = {}
    if request.POST:
        ano = request.POST.get("ano",0)
        semestre = request.POST.get("semestre",0)
        turmas = Turma.objects.filter(disciplina_ofertada__ano=ano, disciplina_ofertada__semestre=semestre)
        for turma in turmas:
            print(turma.alunos)
            
        contexto["turmas"] = turmas
    else:
        pass
    return render(request,"restrito/matricula.html",contexto)

@login_required(login_url="/entrar")
@user_passes_test(check_professor, login_url="/")
def professor(request):
    turmas = Turma.objects.filter(professor__parent_link=request.user)
    for turma in turmas:
        turma.exercicios = Questao.objects.filter(turma=turma)
    contexto = {
        "turmas": turmas
    }
    return render(request,"restrito/professor.html",contexto)

@login_required(login_url="/entrar")
@user_passes_test(check_professor, login_url="/")
def questao_form(request, turma_id, questao_id=None):
    turma = Turma.objects.get(id=turma_id)
    if questao_id:
        qst = Questao.objects.get(id=questao_id)
        numero = qst.numero
    else:
        qst = Questao(turma=turma)
        numero = 'Nova'
    form = QuestaoForm(request.POST or None, request.FILES or None, instance=qst)
    if request.POST and form.is_valid():
        form.save()        
        return redirect(reverse('restrito:professor'))
    
    contexto = {
        "form":form,
        "turma": turma,
        'numero': numero
    }
    return render(request, "restrito/questao.html", contexto)

restrito/templates/restrito/aluno.html
{% extends "restrito/base_restrito.html" %}
{% load static %}

{% block titulo_restrito %}Área do Aluno{% endblock %}

{% block restrito_conteudo %}
      <h2>Turmas</h2>
      <ul>
          {% for turma in turmas %}
            <li>
              {{ turma }}
            </li>
          {% empty %}
            <li>Nenhuma turma ainda!</li>
          {% endfor %}
      </ul>
    </section>
{% endblock  %}

restrito/templates/restrito/base_restrito.html
{% extends "base.html" %}
{% load static %}
{% block scripts %}
    <link rel="stylesheet" href="{% static 'css/restrito.css' %}">
{% endblock %}

{% block main %}
<section class="restrito">
    <header>
      <h1 class="main">{% block titulo_restrito %}Restrito{% endblock %}</h1>
    </header>
    <aside class="submenu">
      <nav>
        <ul>
          <li class="titulo">Opções</li>
          <li><a href="{% url 'restrito:aluno' %}" class="ativo">Principal</a></li>
          <li><a href="{% url 'restrito:matricula' %}">Matrícula</a></li>
        </ul>
      </nav>
    </aside>
    <section class="conteudo">
      {% block restrito_conteudo %}{% endblock %}
    </section>
</section>
{% endblock  %}

restrito/templates/restrito/matricula.html
{% extends "restrito/base_restrito.html" %}
{% load static %}

{% block titulo_restrito %}Matrícula{% endblock %}

{% block restrito_conteudo %}
    <h2>Matrícula</h2>
    <form method="POST">
        {% csrf_token %}
        <label for="buscar_ano">Ano:</label>
        <input id="buscar_ano" name="ano" type="number">
        <label for="buscar_semestre">Semestre:</label>
        <input id="buscar_semestre" name="semestre" type="number">
        <button type="submit">Buscar</button>
    </form>
    {% if not turmas is None %}
      <h3>Turmas disponíveis no Período</h3>
      <ul>
          {% for turma in turmas  %}
            <li>{{ turma }}</li>
          {% empty %}
            <li>Não há ofertas para esse período</li>
          {% endfor %}
      </ul>
    {% endif %}

{% endblock %}

restrito/templates/restrito/professor.html
{% extends "restrito/base_restrito.html" %}
{% load static %}

{% block titulo_restrito %}Área do Professor{% endblock %}

{% block restrito_conteudo %}
    {% if questao %}
      <p>QUestão adicionada com sucesso!</p>
    {% endif %}

      <h2>Turmas</h2>
      {% for turma in turmas %}
        <div class="turma">
          <h3>{{ turma.disciplina_ofertada.disciplina }}</h3>
          <p>Turma: {{turma.disciplina_ofertada.semestre}}{{ turma.identificador }} - {{ turma.turno }}</p>
          <p>Exercícios:
            <ul>
              {% for exercicio in turma.exercicios  %}
                <li>
                  <a href="{% url 'restrito:questao_form' turma_id=turma.id questao_id=exercicio.id %}">
                    #{{ exercicio.numero }} para {{ exercicio.data_limite_entrega}}
                  </a>
                </li>
              {% empty %}
                <li> Não há exercícios </li>
              {% endfor %}
            </ul>
          </p>
          <div class="acoes">
              <a href="{% url 'restrito:questao_form' turma_id=turma.id questao_id='' %}">Adicionar Exercício</a>
          </div>
        </div>
      {% empty %}
        Nenhuma turma ainda!
      {% endfor %}
    </section>
{% endblock  %}

restrito/templates/restrito/questao.html
{% extends "restrito/base_restrito.html" %}
{% load static %}

{% block titulo_restrito %}Área do Professor{% endblock %}

{% block restrito_conteudo %}
      <h2>Questão {{ questao }} </h2>
      <p>Turma: {{ turma.disciplina_ofertada.disciplina }} {{ turma.disciplina_ofertada.semestre}}{{ turma.identificador }} </p>
      <form method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
      </form>
{% endblock  %}